<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>管理</title>
  <!-- Vendor Files -->
  <link href="https://unpkg.com/bootstrap@5.2.0/dist//css/bootstrap.min.css" rel="stylesheet">
  <link href="https://unpkg.com/bootstrap-icons@1.9.1/font/bootstrap-icons.css" rel="stylesheet">
  <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet">

  <script src="https://unpkg.com/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://unpkg.com/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://unpkg.com/x-editable-bs4@1.5.5/dist/bootstrap5-editable/js/bootstrap-editable.min.js"></script>

  <script src="https://unpkg.com/sortablejs-make@1.0.1/Sortable.min.js"></script>
  <script src="https://unpkg.com/jquery-sortablejs@1.0.1/jquery-sortable.js"></script></script>
<style>
  .card {
    border: none;
    border-radius: 5px;
    box-shadow: 0px 0 30px rgb(1 41 112 / 10%);
    margin: 20px 0 15px 0;
  }

  .card-body {
      padding: 20px;
  }

  .card-title {
    padding: 20px 0 15px 0;
    font-size: 18px;
    font-weight: 500;
    color: #e26161;
    font-family: "Poppins", sans-serif;
  }

  .btn-save {
    color: #fff;
    background-color: #e26161;
    border-color: #e26161;
  }

  .btn-save:hover {
    color: #fff;
    background-color: #e26161;
    border-color: #e26161;
  }

  .ellipsis {
     max-width:150px;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
    word-break:keep-all;

  }

  .editable-empty, .editable-empty:hover, .editable-empty:focus {
    font-style: italic;
    color: #CCCCCC;
    /* border-bottom: none; */
    text-decoration: none;
    }

  .editable-click, a.editable-click, a.editable-click:hover {
    text-decoration: none;
    border-bottom: dashed 1px #cccccc;
  }


</style>

</head>

<body>
<div class="container-lg">

