  <div class="card">
    <div class="card-body">
      <h5 class="card-title">编辑</h5>

      <!-- General Form Elements -->
      <form id="form" method="POST" >
        <?php 
        //var_dump($this->fields);
        //var_dump($this->data);
        foreach ($this->fields as $k => $v) { 
          //var_dump($v);
          ?>
          <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label"><?php echo $v['label']; ?> </label>
          <div class="col-sm-10 row">
            <?php if($v['type']=='text' ||$v['type']=='image'){?> 
            <input type="text" name="<?php echo $v['name'];?>" value="<?php echo @$this->data[$v['name']];?>" class="form-control">
            <?php }elseif($v['type']=='date' ||$v['type']=='time'){?> 
            <input type="<?php echo $v['type'];?>" name="<?php echo $v['name'];?>" value="<?php echo @$this->data[$v['name']];?>" class="form-control">
            <?php }elseif($v['type']=='textarea'){ ?>
            <textarea class="form-control" name="<?php echo $v['name'];?>"  style="height: 100px"><?php echo @$this->data[$v['name']];?></textarea>
            <?php }elseif($v['type']=='select'){ ?>
              <select class="form-select" aria-label="Default select example" name="<?php echo @$v['name'];?>">
                 <?php 
                 foreach ($v['options'] as $kk => $vv) { ?>
                      <option <?php echo ($kk==@$this->data[$v['name']])?"selected":"";?> value="<?php echo $kk;?>"><?php echo $vv;?></option>
                  <?php } ?>
              </select>
            <?php }elseif($v['type']=='radio'){ ?>
                  <div class="col-md-12">
                  <?php  foreach ($v['options'] as $kk => $vv) { ?>
                      <div class="form-check-inline">
                        <input class="form-check-input" type="radio" name="<?php echo $v['name'];?>" id="<?php echo $v['name'].$kk;?>" value="<?php echo $kk;?>" <?php echo ($kk==@$this->data[$v['name']])?"checked":"";?>>
                        <label class="form-check-label" for="<?php echo $v['name'].$kk;?>">
                          <?php echo $vv;?>
                        </label>
                      </div>
                      
            <?php   }  ?>
                  </div>
              <?php    }elseif($v['type']=='group'){ 
              //var_dump($v);
                    foreach ($v['fields'] as $kk => $vv) { 
                      ?>
                  <div class="col-md-<?php echo $vv['col'];?> ">
                    <div class="form-floating" style="margin-bottom: 1rem;">
                    <?php if($vv['type']=='text' ||$vv['type']=='image'){?> 
                      <input type="text" name="<?php echo $vv['name'];?>" value="<?php echo @$this->data[$vv['name']];?>"  class="form-control" id="<?php echo $vv['name'].$kk;?>" placeholder="<?php echo $vv['label'];?>">
                      <?php }elseif($vv['type']=='textarea'){ ?>
                      <textarea class="form-control" name="<?php echo $vv['name'];?>"  style="height: 100px" id="<?php echo $vv['name'].$kk;?>" placeholder="<?php echo $vv['label'];?>"><?php echo @$this->data[$vv['name']];?></textarea>
                      <?php }elseif($vv['type']=='select'){ ?>
                        <select class="form-select" aria-label="Default select example" name="<?php echo $vv['name'];?>">
                           <?php 
                           foreach ($vv['options'] as $kkk => $vvv) { ?>
                                <option <?php echo ($kkk==@$this->data[$vv['name']])?"selected":"";?> value="<?php echo $kkk;?>"><?php echo $vvv;?></option>
                            <?php } ?>
                        </select>
                      <?php }elseif($vv['type']=='radio'){ 

                              foreach ($vv['options'] as $kkk => $vvv) { ?>
                                <div class="form-check-inline">
                                  <input class="form-check-input" type="radio" name="<?php echo $vv['name'];?>" id="<?php echo $vv['name'].$kkk;?>" value="<?php echo $kkk;?>" <?php echo ($kkk==@$this->data[$vv['name']])?"checked":"";?>>
                                  <label class="form-check-label" for="<?php echo $vv['name'].$kkk;?>">
                                    <?php echo $vvv;?>
                                  </label>
                                </div>
                                
                      <?php   }  

                          }?>
                        <label for="<?php echo $vv['name'].$kk;?>"><?php echo $vv['label'];?></label>
                      </div>
                    </div>
            <?php   }  

                  } ?>

          </div>
        </div>
        <?php } ?>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label"> </label>
          <div class="col-sm-10">
            <button type="submit" class="btn btn-save">保存</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
  </div>



<script >

const form = document.getElementById('form');

form.addEventListener('submit', event => {
  event.preventDefault();
  const formData = new FormData(form);
  var objData = {};

  formData.forEach((value, key) => objData[key] = value);

  $.ajax({
    url: $(this).data('url'),
    data: JSON.stringify(objData),
    method: "post",
    dataType: "json",
    contentType: 'application/json',
    success: function (data) {
      console.log(data)
      if (data.code == 0) {

        var toastLiveExample = document.getElementById('liveToast')
        var toast = new bootstrap.Toast(toastLiveExample)

        toast.show()
      } 

      if (data.redirect ===true) {
        
        window.location.href = data.url;
      } 
    }
  });


})


</script>